### ISSUE TITLE
Замечания по lw1

### ISSUE THREAD

**Issue by lulldev** [OhMyTlswp/homework#1]
нарушен стиль форматирования

<img width="447" alt="Screen Shot 2019-09-13 at 15 35 39" src="https://user-images.githubusercontent.com/15219574/64862845-3067c680-d63c-11e9-9819-b5ee495e7640.png">

**Comment by lulldev** [comment]
```css 
.email-container{
	max-width: 600px; 
	margin: 0 auto;
}
```
поправить `{`, `,` отступы
